ALTER TABLE "Game" ADD COLUMN "mode" TEXT NOT NULL DEFAULT 'standard';
ALTER TABLE "Player" ADD COLUMN "isBot" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Player" ADD COLUMN "botType" TEXT NOT NULL DEFAULT 'balanced';
