export const ACCOUNT_NAMES_VI = {
  CASH: 'Tiền mặt',
  DEPOSIT: 'Tiền gửi ngân hàng',
  LAND: 'Đất',
  BUILDINGS: 'Công trình (nguyên giá)',
  ACC_DEPR: 'Hao mòn lũy kế',
  GOODWILL: 'Lợi thế thương mại',
  BANK_LOAN: 'Vay ngân hàng',
  BONDS_PAYABLE: 'Trái phiếu phát hành',
  TAX_PAYABLE: 'Thuế phải nộp',
  ARREARS: 'Nợ quá hạn',
  PAID_IN_CAPITAL: 'Vốn góp',
  RETAINED_EARNINGS: 'Lợi nhuận giữ lại',
  REVENUE: 'Doanh thu',
  INTEREST_INCOME: 'Lãi tiền gửi',
  REVAL_GAIN: 'Lãi đánh giá lại đất',
  BARGAIN_GAIN: 'Lãi mua rẻ',
  DISPOSAL_GAIN: 'Lãi thanh lý ô đất',
  COGS: 'Giá vốn',
  WAGES: 'Lương',
  MAINTENANCE: 'Bảo trì',
  RND: 'R&D / Tái đầu tư',
  DEPRECIATION: 'Khấu hao',
  INTEREST_EXPENSE: 'Lãi vay & coupon',
  TAX_EXPENSE: 'Thuế TNDN',
  IDLE_LAND_TAX: 'Thuế đất trống',
  HR_COSTS: 'Chi phí tuyển/thôi việc',
  REVAL_LOSS: 'Lỗ đánh giá lại đất',
  DISPOSAL_LOSS: 'Lỗ thanh lý ô đất',
  FEES: 'Phí phát hành & khác',
};

export const CATEGORY_NAMES_VI = {
  operating: 'Hoạt động kinh doanh',
  investing: 'Đầu tư',
  financing: 'Tài chính',
  tax: 'Thuế',
  transfer: 'Chuyển khoản nội bộ',
  system: 'Hệ thống',
};
